import Head from 'next/head'
import Image from 'next/image';
// import Eric from '/Eric.JPG';

export default function Home() {
    return (
      <div>
      <Head>
     <title>Eric's Website</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
   </Head>

 <main className="bg-white px-10 md:px-20 lg:px-40  ">
     
   <section className=" min-h-screen ">

   <nav className="py-3 mb-12 flex justify-between p-3 border-gray-100 rounded bg-gray-300 dark:bg-gray dark:border-gray-700">
       <h1 className="text-xl font-burtons mt-3 mx-3 cursor-pointer"><a href='/'>Eric's Website</a></h1>
       <ul className="flex items-center">
         <li className='items-center'>
         <button className="cursor-pointer bg-primary shadow-xl text-black px-5 py-2 rounded-xl ml-10"><a href='/quiz1/profile'>Profile</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/hometown'>Hometown</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/food'>Food</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/tourist'>Tourist</a></button> 

           </li>
       </ul>
     </nav>
     <div>
     <h1 className="text-5xl py-3 text-center text-green-600 animate-pulse">Food</h1>
     </div>
     <div className="flex mt-5">
     <div className="relative rounded-full w-80 h-80 overflow-hidden">
        <Image src="/kerak-telor.jpeg" alt="" layout="fill" objectFit="cover"/>
      </div>
      <div className="border-4 w-7/12 border-red-500 h-min ml-24 mt-10">
        <h1 className="text-center mt-5 text-3xl">KERAK TELOR</h1>
        <h3 className="ml-5 mr-5 mt-5 text-justify mb-5">Kerak telor is a Betawi traditional spicy omelette dish in Indonesian cuisine. 
          It is made from glutinous rice cooked with egg and served with serundeng, fried shallots and dried shrimp as topping. 
          It is considered as a snack and not as a main dish.</h3>
      </div>
     </div>
     <div className="flex mt-5">
     <div className="relative rounded-full w-80 h-80 overflow-hidden">
        <Image src="/nasiuduk.jpeg" alt="" layout="fill" objectFit="cover"/>
      </div>
      <div className="border-4 w-7/12 border-blue-500 h-min ml-24 mt-10">
        <h1 className="text-center mt-5 text-3xl">NASI UDUK</h1>
        <h3 className="ml-5 mr-5 mt-5 text-justify mb-5">Nasi uduk is an Indonesian style steamed rice cooked in coconut milk dish, 
        especially popular in Betawi cuisine. According to the book "Kuliner Betawi Selaksa Rasa & Cerita" (2016) 
        composed by Akademi Kuliner Indonesia, the term uduk etymology derived from the term that means "difficult" or "struggle", 
        which suggested that this rice dish was originally consumed by farmers and hard labourers.
        Another theory suggests that the term uduk is related to the term aduk which means "mix", thus nasi uduk means 
        "mixed rice".</h3>
      </div>
     </div>
     </section>
     
     </main>

     
     </div>
        

    )
}