import Head from 'next/head'
import Image from 'next/image';
// import Eric from '/Eric.JPG';

export default function Home() {
    return (
      <div>
         <Head>
        <title>Eric's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className="bg-white px-10 md:px-20 lg:px-40  ">
        
      <section className=" min-h-screen ">

      <nav className="py-3 mb-12 flex justify-between p-3 border-gray-100 rounded bg-gray-300 dark:bg-gray dark:border-gray-700">
          <h1 className="text-xl font-burtons mt-3 mx-3 cursor-pointer"><a href='/'>Eric's Website</a></h1>
          <ul className="flex items-center">
            <li className='items-center'>
            <button className="cursor-pointer bg-primary shadow-xl text-black px-5 py-2 rounded-xl ml-10"><a href='/quiz1/profile'>Profile</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/hometown'>Hometown</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/food'>Food</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/tourist'>Tourist</a></button> 
            </li>
          </ul>
        </nav>

        <section>
          <div className="flex gap-5">
            <div className="border-4 box-border max-h-fit outline-4 rounded-xl w-8/12 p-4 border-red-500 relative opacity-70 bg-bottom">
            <h1 className="text-9xl py-3 text-center text-blue-500 mb-10 border-y-5">JAKARTA</h1>
            <h3 className="text-black text-justify">Jakarta, Indonesia's massive capital, sits on the northwest coast of the island of Java. 
              A historic mix of cultures – Javanese, Malay, Chinese, Arab, Indian and European – has influenced its architecture, 
              language and cuisine. The old town, Kota Tua, is home to Dutch colonial buildings, Glodok (Jakarta’s Chinatown) 
              and the old port of Sunda Kelapa, where traditional wooden schooners dock.</h3>
            </div>
            <div className="border-4 box-border max-h-fit outline-4 rounded-xl w-4/12 p-4 border-purple-500 relative">
              <Image src="/monas3.jpeg" alt="" layout="fill" objectFit="cover"/>
            </div>
            </div>
            <div className="border-4 box-border w-12/12 h-max border-green-500 my-10 rounded-xl">
              <h3 className="my-3 ml-3 text-justify mr-3">The National Monument (Indonesian: Monumen Nasional, abbreviated Monas) is a 132 m (433 ft) 
              obelisk in the centre of Merdeka Square, Central Jakarta, symbolizing the fight for Indonesia. It is the national 
              monument of the Republic of Indonesia, built to commemorate the struggle for Indonesian independence.

                Construction began in 1961 under the direction of President Sukarno. Monas was opened to the public in 1975. 
                It is topped by a flame covered with gold foil.

                The monument and the museum are open daily from 08.00 until 16.00 Western 
                Indonesia Time (UTC+7) throughout the week except for the Mondays when the monument is closed. 
                Since April 2016, the monument also opens during night time, from 19.00 until 22.00 on Tuesday to Friday, 
                and from 19.00 until 00.00 on Saturday and Sunday</h3>

            
            </div>
        </section>
        </section>
        
        </main>

        
        </div>
    )
}