import Head from 'next/head'
import Image from 'next/image';
// import Eric from '/Eric.JPG';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillInstagram} from "react-icons/ai";

export default function Home() {
    return (
      <div>
      <Head>
     <title>Eric's Website</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
   </Head>

 <main className="bg-white px-10 md:px-20 lg:px-40  ">
     
   <section className=" min-h-screen ">

      <nav className="py-3 mb-12 flex justify-between p-3 border-gray-100 rounded bg-gray-300 dark:bg-gray dark:border-gray-700">
       <h1 className="text-xl font-burtons mt-3 mx-3 cursor-pointer"><a href='/'>Eric's Website</a></h1>
       <ul className="flex items-center">
         <li className='items-center'>
         <button className="cursor-pointer bg-primary shadow-xl text-black px-5 py-2 rounded-xl ml-10"><a href='/quiz1/profile'>Profile</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/hometown'>Hometown</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/food'>Food</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/tourist'>Tourist</a></button> 

           </li>
       </ul>
     </nav>

     <section>
      <div>
         <h1 className="text-5xl py-3 text-center text-green-600 animate-ping">Profile</h1>
         <h3 className="text-lg py-2 md:text-lg text-center">Just An Ordinary University Student</h3>
          <div className="shadow-xl p-10 rounded-xl flex justify-center items-center gap-40 -bottom-10">
            <div className="relative mx-5 rounded-full w-80 h-80 mt-12 overflow-hidden">
              <Image src="/FOTO.JPG" alt="" layout="fill" objectFit="cover"/>
            </div>
            <div>
              <div className="border-y-5">
              <h1>Name: Eric Azka Nugroho</h1>
              <h2>DOB: 1 January 2003</h2>
              <h2>Birth Place: Jakarta, Indonesia</h2>
              <h2>Current Studies: Institute Technology of Sepuluh Nopember</h2>
              </div>
              <div className="cursor-pointer text-4xl flex justify-center gap-10 py-3 text-gray-800 my-5">
          <AiFillTwitterCircle/>
          <AiFillLinkedin />
          <AiFillGithub />
          <AiFillInstagram />
        </div>
            </div>
          </div>
        </div>
    </section>


    </section>
     
     </main>

     
     </div>
        

    )
}