import Head from 'next/head'
import Image from 'next/image';
// import Eric from '/Eric.JPG';

export default function Home() {
    return (
      <div>
      <Head>
     <title>Eric's Website</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
   </Head>

 <main className="bg-white px-10 md:px-20 lg:px-40  ">
     
   <section className=" min-h-screen ">

   <nav className="py-3 mb-12 flex justify-between p-3 border-gray-100 rounded bg-gray-300 dark:bg-gray dark:border-gray-700">
       <h1 className="text-xl font-burtons mt-3 mx-3 cursor-pointer"><a href='/'>Eric's Website</a></h1>
       <ul className="flex items-center">
         <li className='items-center'>
         <button className="cursor-pointer bg-primary shadow-xl text-black px-5 py-2 rounded-xl ml-10"><a href='/quiz1/profile'>Profile</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/hometown'>Hometown</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/food'>Food</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/tourist'>Tourist</a></button> 

           </li>
       </ul>
     </nav>

      <div>
      
     <h1 className="text-5xl py-3 text-center text-green-600 animate-bounce line-through decoration-sky-500">Tourist</h1>


     </div> 
     <div className="flex gap-5">
     <div className="my-24 border-4 box-border h-72 outline-4 rounded-xl w-4/12 p-4 border-purple-500 relative">
      <Image src="/tmii.jpeg" alt="" layout="fill" objectFit="cover"/>
      </div>
      <div className="border-4 box-border w-8/12 h-max border-green-500 my-32 rounded-xl">
              <h3 className="my-3 ml-3 text-justify mr-3">
                Taman Mini "Indonesia Indah" (literally "Beautiful Indonesia" Mini Park—the apostrophes are in the 
                name—abbreviated as TMII) is a culture-based recreational area located in East Jakarta, Indonesia. 
                Since July 2021, it is operated by PT Taman Wisata Candi Borobudur, Prambanan, dan Ratu Boko, a subsidiary 
                of the state-owned tourism holding company InJourney. It was operated by Yayasan Harapan Kita, 
                a foundation established by Siti Hartinah, the first lady during most of the New Order and wife of Suharto, 
                and run by Suharto's descendants since his death until 2021. It has an area of about 100 hectares (250 acres).
                </h3>
            </div>
      
     </div>
      


     
     </section>
     </main>

     
     </div>
        

    )
}