import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillInstagram} from "react-icons/ai";
import {GiSoccerBall} from "react-icons/gi";
import {IoMdCodeWorking} from "react-icons/io";
import { BsPhoneLandscapeFill } from 'react-icons/bs';
import Image from 'next/image';
//import Eric from '../public/Eric.JPG';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eric's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40  ">
        
        <section className=" min-h-screen ">

        <nav className="py-3 mb-12 flex justify-between p-3 border-gray-100 rounded bg-gray-300 dark:bg-gray dark:border-gray-700">
          <h1 className="text-xl font-burtons mt-3 mx-3 cursor-pointer"><a href='/'>Eric's Website</a></h1>
          <ul className="flex items-center">
            <li className='items-center'>
            <button className="cursor-pointer bg-primary shadow-xl text-black px-5 py-2 rounded-xl ml-10"><a href='/quiz1/profile'>Profile</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/hometown'>Hometown</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/food'>Food</a></button>
              <button className="cursor-pointer bg-primary shadow-xl text-black  px-5 py-2 rounded-xl ml-10"><a href='/quiz1/tourist'>Tourist</a></button> 

              </li>
          </ul>
        </nav>


        <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-green-600 font-medium md:text-6xl animate-bounce">Eric Azka Nugroho</h2>
          <h3 className="text-2xl py-2 md:text-3xl">Just An Ordinary University Student</h3>
          <p className="text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">This portfolio website is my first project of creating a website using HTML and Tailwind CSS. Enjoy!</p>
        </div>
        <div className="cursor-pointer text-5xl flex justify-center gap-10 py-3 text-gray-800">
          <AiFillTwitterCircle />
          <AiFillLinkedin />
          <AiFillGithub />
          <AiFillInstagram />
        </div>
        <div className="relative mx-auto rounded-full w-80 h-80 mt-12 overflow-hidden">
        <Image src="/Eric.JPG" alt="" layout="fill" objectFit="cover"/>
        </div>
        </section>

        <section>
          <div className="shadow-lg p-10 rounded-xl ">
            <h3 className="text-3xl py-3">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 text-justify">

              I was born as a digital native. I cannot remember a time when I did not interact with <span className="text-green-600">technology </span>. 
              To see life without technology in this era would be meaningless.
               The existence of <span className="text-green-600">technology makes our life easier and simpler. </span> 
               I remember how my parents said that it took them several more steps and efforts to find information, compared to the current days. 
               Today, it only takes a  <span className="text-green-600">few clicks away and we can get what we want.  </span>
               So simple. However, behind the simplicity, there is a process that I would like to learn and which is why I create this <span className="text-green-600"> website.</span>

              </p>
            
          </div>
        
        </section>

        <section>
        <div>
            <h3 className="text-3xl py-1 dark:text-black text-center my-16">What I do in my Free Time</h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <div className="text-5xl flex justify-center gap-10 py-3 text-gray-800">
            <GiSoccerBall/>
        </div>
            
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Sports
              </h3>
              <p className="py-2">
                Playing sports 
              </p>
              <h4 className="py-4 text-teal-600">Sports that I liked</h4>
              <p className="text-gray-800 py-1">Soccer</p>
              <p className="text-gray-800 py-1">Basketball</p>
              <p className="text-gray-800 py-1">Swimming</p>
              <p className="text-gray-800 py-1">Volley</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <div className="text-5xl flex justify-center gap-10 py-3 text-gray-800">
            <BsPhoneLandscapeFill/>
        </div>
              
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Watching TV Series
              </h3>
              <p className="py-2">
                I love to watch TV series in my free time
              </p>
              <h4 className="py-4 text-teal-600">TV Series</h4>
              <p className="text-gray-800 py-1">Friends</p>
              <p className="text-gray-800 py-1">How I Met Your Mother</p>
              <p className="text-gray-800 py-1">Vikings</p>
              <p className="text-gray-800 py-1">Big Bang Theory</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <div className="text-5xl flex justify-center gap-10 py-3 text-gray-800">
            <IoMdCodeWorking/>
        </div>
            
              <h3 className="text-lg font-medium pt-8 pb-2 ">Programming</h3>
              <p className="py-2">
                I love to code 
              </p>
              <h4 className="py-4 text-teal-600">Language that I learned</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">C</p>
              <p className="text-gray-800 py-1">C++</p>
            </div>
          </div>
        </section>

      </main>

    </div>
  )
}
